version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
