name: "continuous integration"

on:
  pull_request:
  push:
    branches:
      - "main"
      - "renovate/*"

env:
  MIN_MSI: 95.00
  MIN_COVERED_MSI: 98.00

jobs:
  phpunit-tests:
    name: "phpunit tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4

      - name: "install php"
        uses: "shivammathur/setup-php@2.26.0"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "install dependencies"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "tests"
        run: "vendor/bin/phpunit --exclude=ci-borked --coverage-clover=coverage.xml"

  mutation-tests:
    name: "mutation tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4

      - name: "install php"
        uses: "shivammathur/setup-php@2.26.0"
        with:
          coverage: "xdebug"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1, zend.assertions=1

      - name: "install dependencies"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "infection"
        run: "./vendor/bin/infection -j$(nproc) --logger-github --min-msi=$MIN_MSI --min-covered-msi=$MIN_COVERED_MSI --test-framework-options='--testsuite=unit --exclude=ci-borked'"
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  coding-standards:
    name: "php cs fixer"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4

      - name: "install PHP"
        uses: "shivammathur/setup-php@2.26.0"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr, php-cs-fixer

      - name: "install dependencies"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "php cs fixer dry run"
        run: "php-cs-fixer fix --dry-run --format=checkstyle | cs2pr"